model: 'm'
scale: 2
rgb_range: 255
colors: 3
n_lgab: 24
c_lgan: 60
n_share: 0
r_expand: 2
act_type: 'gelu'
#act_type: 'relu'
#act_type: 'silu'
#optim: 'lamb'
optim: 'adam'
fp: 32
loss: 'SmoothL1Loss'
#loss: 'L1Loss'
window_sizes: [15,10,5]
pretrain:

## parameters for model training
patch_size: 60
batch_size: 64
data_repeat: 80
data_augment: 1

epochs: 1000
lr: 0.0002
decays: [500,800,900,950]
gamma: 0.5
log_every: 100
test_every: 1
log_path: "./experiments"
log_name:

## hardware specification
gpu_ids: [1]

## data specification
data_path: './SR_datasets'
eval_sets: ['Set5', 'Set14']
#eval_sets: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']
